
enum TRRegion { Akdeniz, Ege, Marmara, IcAnadolu, Karadeniz, DoguAnadolu, GuneydoguAnadolu, Bilinmiyor }


const Map<String, TRRegion> ilToRegion = {

  'Antalya': TRRegion.Akdeniz,
  'Mersin': TRRegion.Akdeniz,
  'Adana': TRRegion.Akdeniz,
  'Hatay': TRRegion.Akdeniz,
  'Osmaniye': TRRegion.Akdeniz,
  'Kahramanmaraş': TRRegion.Akdeniz,
  'Isparta': TRRegion.Akdeniz,
  'Burdur': TRRegion.Akdeniz,


  'İzmir': TRRegion.Ege,
  'Aydın': TRRegion.Ege,
  'Muğla': TRRegion.Ege,
  'Manisa': TRRegion.Ege,
  'Uşak': TRRegion.Ege,
  'Kütahya': TRRegion.Ege,
  'Afyonkarahisar': TRRegion.Ege,
  'Denizli': TRRegion.Ege,

  'İstanbul': TRRegion.Marmara,
  'Edirne': TRRegion.Marmara,
  'Kırklareli': TRRegion.Marmara,
  'Tekirdağ': TRRegion.Marmara,
  'Çanakkale': TRRegion.Marmara,
  'Balıkesir': TRRegion.Marmara,
  'Bursa': TRRegion.Marmara,
  'Yalova': TRRegion.Marmara,
  'Bilecik': TRRegion.Marmara,
  'Kocaeli': TRRegion.Marmara,
  'Sakarya': TRRegion.Marmara,

  'Ankara': TRRegion.IcAnadolu,
  'Konya': TRRegion.IcAnadolu,
  'Eskişehir': TRRegion.IcAnadolu,
  'Kayseri': TRRegion.IcAnadolu,
  'Sivas': TRRegion.IcAnadolu,
  'Aksaray': TRRegion.IcAnadolu,
  'Karaman': TRRegion.IcAnadolu,
  'Kırıkkale': TRRegion.IcAnadolu,
  'Kırşehir': TRRegion.IcAnadolu,
  'Nevşehir': TRRegion.IcAnadolu,
  'Niğde': TRRegion.IcAnadolu,
  'Yozgat': TRRegion.IcAnadolu,
  'Çankırı': TRRegion.IcAnadolu,

  'Samsun': TRRegion.Karadeniz,
  'Trabzon': TRRegion.Karadeniz,
  'Ordu': TRRegion.Karadeniz,
  'Giresun': TRRegion.Karadeniz,
  'Rize': TRRegion.Karadeniz,
  'Artvin': TRRegion.Karadeniz,
  'Gümüşhane': TRRegion.Karadeniz,
  'Bayburt': TRRegion.Karadeniz,
  'Tokat': TRRegion.Karadeniz,
  'Amasya': TRRegion.Karadeniz,
  'Çorum': TRRegion.Karadeniz,
  'Bartın': TRRegion.Karadeniz,
  'Zonguldak': TRRegion.Karadeniz,
  'Karabük': TRRegion.Karadeniz,
  'Kastamonu': TRRegion.Karadeniz,
  'Sinop': TRRegion.Karadeniz,
  'Bolu': TRRegion.Karadeniz,
  'Düzce': TRRegion.Karadeniz,

  'Erzurum': TRRegion.DoguAnadolu,
  'Erzincan': TRRegion.DoguAnadolu,
  'Kars': TRRegion.DoguAnadolu,
  'Ardahan': TRRegion.DoguAnadolu,
  'Iğdır': TRRegion.DoguAnadolu,
  'Ağrı': TRRegion.DoguAnadolu,
  'Van': TRRegion.DoguAnadolu,
  'Bitlis': TRRegion.DoguAnadolu,
  'Hakkari': TRRegion.DoguAnadolu,
  'Malatya': TRRegion.DoguAnadolu,
  'Elazığ': TRRegion.DoguAnadolu,
  'Tunceli': TRRegion.DoguAnadolu,
  'Bingöl': TRRegion.DoguAnadolu,
  'Muş': TRRegion.DoguAnadolu,

  'Gaziantep': TRRegion.GuneydoguAnadolu,
  'Şanlıurfa': TRRegion.GuneydoguAnadolu,
  'Diyarbakır': TRRegion.GuneydoguAnadolu,
  'Mardin': TRRegion.GuneydoguAnadolu,
  'Batman': TRRegion.GuneydoguAnadolu,
  'Siirt': TRRegion.GuneydoguAnadolu,
  'Şırnak': TRRegion.GuneydoguAnadolu,
  'Kilis': TRRegion.GuneydoguAnadolu,
  'Adıyaman': TRRegion.GuneydoguAnadolu,
};
